public enum ContainerPrototypeName: String, PrototypeName {
    case baitChest = "bait-chest"
    case bigShipWreck1 = "big-ship-wreck-1"
    case bigShipWreck2 = "big-ship-wreck-2"
    case bigShipWreck3 = "big-ship-wreck-3"
    case blueChest = "blue-chest"
    case crashSiteChest1 = "crash-site-chest-1"
    case crashSiteChest2 = "crash-site-chest-2"
    case crashSiteSpaceship = "crash-site-spaceship"
    case crashSiteSpaceshipWreckBig1 = "crash-site-spaceship-wreck-big-1"
    case crashSiteSpaceshipWreckBig2 = "crash-site-spaceship-wreck-big-2"
    case crashSiteSpaceshipWreckMedium1 = "crash-site-spaceship-wreck-medium-1"
    case crashSiteSpaceshipWreckMedium2 = "crash-site-spaceship-wreck-medium-2"
    case crashSiteSpaceshipWreckMedium3 = "crash-site-spaceship-wreck-medium-3"
    case ironChest = "iron-chest"
    case redChest = "red-chest"
    case steelChest = "steel-chest"
    case woodenChest = "wooden-chest"
}