public enum ItemPrototypeName: String, PrototypeName {
    case accumulator
    case advancedCircuit = "advanced-circuit"
    case arithmeticCombinator = "arithmetic-combinator"
    case artilleryTurret = "artillery-turret"
    case assemblingMachine1 = "assembling-machine-1"
    case assemblingMachine2 = "assembling-machine-2"
    case assemblingMachine3 = "assembling-machine-3"
    case battery
    case batteryEquipment = "battery-equipment"
    case batteryMk2Equipment = "battery-mk2-equipment"
    case beacon
    case beltImmunityEquipment = "belt-immunity-equipment"
    case bigElectricPole = "big-electric-pole"
    case boiler
    case burnerGenerator = "burner-generator"
    case burnerInserter = "burner-inserter"
    case burnerMiningDrill = "burner-mining-drill"
    case centrifuge
    case chemicalPlant = "chemical-plant"
    case coal
    case coin
    case computer
    case concrete
    case constantCombinator = "constant-combinator"
    case constructionRobot = "construction-robot"
    case copperCable = "copper-cable"
    case copperOre = "copper-ore"
    case copperPlate = "copper-plate"
    case crashSiteAssemblingMachine1Broken = "crash-site-assembling-machine-1-broken"
    case crashSiteAssemblingMachine1Repaired = "crash-site-assembling-machine-1-repaired"
    case crashSiteAssemblingMachine2Broken = "crash-site-assembling-machine-2-broken"
    case crashSiteAssemblingMachine2Repaired = "crash-site-assembling-machine-2-repaired"
    case crashSiteChest1 = "crash-site-chest-1"
    case crashSiteChest2 = "crash-site-chest-2"
    case crashSiteElectricPole = "crash-site-electric-pole"
    case crashSiteGenerator = "crash-site-generator"
    case crashSiteLabBroken = "crash-site-lab-broken"
    case crashSiteLabRepaired = "crash-site-lab-repaired"
    case crudeOilBarrel = "crude-oil-barrel"
    case deciderCombinator = "decider-combinator"
    case dischargeDefenseEquipment = "discharge-defense-equipment"
    case electricEnergyInterface = "electric-energy-interface"
    case electricEngineUnit = "electric-engine-unit"
    case electricFurnace = "electric-furnace"
    case electricMiningDrill = "electric-mining-drill"
    case electronicCircuit = "electronic-circuit"
    case emptyBarrel = "empty-barrel"
    case energyShieldEquipment = "energy-shield-equipment"
    case energyShieldMk2Equipment = "energy-shield-mk2-equipment"
    case engineUnit = "engine-unit"
    case exoskeletonEquipment = "exoskeleton-equipment"
    case explosives
    case expressLoader = "express-loader"
    case expressSplitter = "express-splitter"
    case expressTransportBelt = "express-transport-belt"
    case expressUndergroundBelt = "express-underground-belt"
    case fastInserter = "fast-inserter"
    case fastLoader = "fast-loader"
    case fastSplitter = "fast-splitter"
    case fastTransportBelt = "fast-transport-belt"
    case fastUndergroundBelt = "fast-underground-belt"
    case filterInserter = "filter-inserter"
    case flamethrowerTurret = "flamethrower-turret"
    case flyingRobotFrame = "flying-robot-frame"
    case fusionReactorEquipment = "fusion-reactor-equipment"
    case gate
    case greenWire = "green-wire"
    case gunTurret = "gun-turret"
    case hazardConcrete = "hazard-concrete"
    case heatExchanger = "heat-exchanger"
    case heatInterface = "heat-interface"
    case heatPipe = "heat-pipe"
    case heavyOilBarrel = "heavy-oil-barrel"
    case infinityChest = "infinity-chest"
    case infinityPipe = "infinity-pipe"
    case inserter
    case ironChest = "iron-chest"
    case ironGearWheel = "iron-gear-wheel"
    case ironOre = "iron-ore"
    case ironPlate = "iron-plate"
    case ironStick = "iron-stick"
    case itemUnknown = "item-unknown"
    case lab
    case landMine = "land-mine"
    case landfill
    case laserTurret = "laser-turret"
    case lightOilBarrel = "light-oil-barrel"
    case loader
    case logisticChestActiveProvider = "logistic-chest-active-provider"
    case logisticChestBuffer = "logistic-chest-buffer"
    case logisticChestPassiveProvider = "logistic-chest-passive-provider"
    case logisticChestRequester = "logistic-chest-requester"
    case logisticChestStorage = "logistic-chest-storage"
    case logisticRobot = "logistic-robot"
    case longHandedInserter = "long-handed-inserter"
    case lowDensityStructure = "low-density-structure"
    case lubricantBarrel = "lubricant-barrel"
    case mediumElectricPole = "medium-electric-pole"
    case nightVisionEquipment = "night-vision-equipment"
    case nuclearFuel = "nuclear-fuel"
    case nuclearReactor = "nuclear-reactor"
    case offshorePump = "offshore-pump"
    case oilRefinery = "oil-refinery"
    case personalLaserDefenseEquipment = "personal-laser-defense-equipment"
    case personalRoboportEquipment = "personal-roboport-equipment"
    case personalRoboportMk2Equipment = "personal-roboport-mk2-equipment"
    case petroleumGasBarrel = "petroleum-gas-barrel"
    case pipe
    case pipeToGround = "pipe-to-ground"
    case plasticBar = "plastic-bar"
    case playerPort = "player-port"
    case powerSwitch = "power-switch"
    case processingUnit = "processing-unit"
    case programmableSpeaker = "programmable-speaker"
    case pump
    case pumpjack
    case radar
    case railChainSignal = "rail-chain-signal"
    case railSignal = "rail-signal"
    case redWire = "red-wire"
    case refinedConcrete = "refined-concrete"
    case refinedHazardConcrete = "refined-hazard-concrete"
    case roboport
    case rocketControlUnit = "rocket-control-unit"
    case rocketFuel = "rocket-fuel"
    case rocketPart = "rocket-part"
    case rocketSilo = "rocket-silo"
    case satellite
    case simpleEntityWithForce = "simple-entity-with-force"
    case simpleEntityWithOwner = "simple-entity-with-owner"
    case smallElectricPole = "small-electric-pole"
    case smallLamp = "small-lamp"
    case smallPlane = "small-plane"
    case solarPanel = "solar-panel"
    case solarPanelEquipment = "solar-panel-equipment"
    case solidFuel = "solid-fuel"
    case splitter
    case stackFilterInserter = "stack-filter-inserter"
    case stackInserter = "stack-inserter"
    case steamEngine = "steam-engine"
    case steamTurbine = "steam-turbine"
    case steelChest = "steel-chest"
    case steelFurnace = "steel-furnace"
    case steelPlate = "steel-plate"
    case stone
    case stoneBrick = "stone-brick"
    case stoneFurnace = "stone-furnace"
    case stoneWall = "stone-wall"
    case storageTank = "storage-tank"
    case substation
    case sulfur
    case sulfuricAcidBarrel = "sulfuric-acid-barrel"
    case trainStop = "train-stop"
    case transportBelt = "transport-belt"
    case undergroundBelt = "underground-belt"
    case uranium235 = "uranium-235"
    case uranium238 = "uranium-238"
    case uraniumFuelCell = "uranium-fuel-cell"
    case uraniumOre = "uranium-ore"
    case usedUpUraniumFuelCell = "used-up-uranium-fuel-cell"
    case waterBarrel = "water-barrel"
    case wood
    case woodenChest = "wooden-chest"
}