public enum RecipePrototypeName: String, PrototypeName {
    case accumulator
    case advancedCircuit = "advanced-circuit"
    case advancedOilProcessing = "advanced-oil-processing"
    case arithmeticCombinator = "arithmetic-combinator"
    case artilleryShell = "artillery-shell"
    case artilleryTargetingRemote = "artillery-targeting-remote"
    case artilleryTurret = "artillery-turret"
    case artilleryWagon = "artillery-wagon"
    case assemblingMachine1 = "assembling-machine-1"
    case assemblingMachine2 = "assembling-machine-2"
    case assemblingMachine3 = "assembling-machine-3"
    case atomicBomb = "atomic-bomb"
    case automationSciencePack = "automation-science-pack"
    case basicOilProcessing = "basic-oil-processing"
    case battery
    case batteryEquipment = "battery-equipment"
    case batteryMk2Equipment = "battery-mk2-equipment"
    case beacon
    case beltImmunityEquipment = "belt-immunity-equipment"
    case bigElectricPole = "big-electric-pole"
    case boiler
    case burnerInserter = "burner-inserter"
    case burnerMiningDrill = "burner-mining-drill"
    case cannonShell = "cannon-shell"
    case car
    case cargoWagon = "cargo-wagon"
    case centrifuge
    case chemicalPlant = "chemical-plant"
    case chemicalSciencePack = "chemical-science-pack"
    case cliffExplosives = "cliff-explosives"
    case clusterGrenade = "cluster-grenade"
    case coalLiquefaction = "coal-liquefaction"
    case combatShotgun = "combat-shotgun"
    case concrete
    case constantCombinator = "constant-combinator"
    case constructionRobot = "construction-robot"
    case copperCable = "copper-cable"
    case copperPlate = "copper-plate"
    case deciderCombinator = "decider-combinator"
    case defenderCapsule = "defender-capsule"
    case destroyerCapsule = "destroyer-capsule"
    case dischargeDefenseEquipment = "discharge-defense-equipment"
    case dischargeDefenseRemote = "discharge-defense-remote"
    case distractorCapsule = "distractor-capsule"
    case effectivityModule = "effectivity-module"
    case effectivityModule2 = "effectivity-module-2"
    case effectivityModule3 = "effectivity-module-3"
    case electricEnergyInterface = "electric-energy-interface"
    case electricEngineUnit = "electric-engine-unit"
    case electricFurnace = "electric-furnace"
    case electricMiningDrill = "electric-mining-drill"
    case electronicCircuit = "electronic-circuit"
    case emptyBarrel = "empty-barrel"
    case emptyCrudeOilBarrel = "empty-crude-oil-barrel"
    case emptyHeavyOilBarrel = "empty-heavy-oil-barrel"
    case emptyLightOilBarrel = "empty-light-oil-barrel"
    case emptyLubricantBarrel = "empty-lubricant-barrel"
    case emptyPetroleumGasBarrel = "empty-petroleum-gas-barrel"
    case emptySulfuricAcidBarrel = "empty-sulfuric-acid-barrel"
    case emptyWaterBarrel = "empty-water-barrel"
    case energyShieldEquipment = "energy-shield-equipment"
    case energyShieldMk2Equipment = "energy-shield-mk2-equipment"
    case engineUnit = "engine-unit"
    case exoskeletonEquipment = "exoskeleton-equipment"
    case explosiveCannonShell = "explosive-cannon-shell"
    case explosiveRocket = "explosive-rocket"
    case explosiveUraniumCannonShell = "explosive-uranium-cannon-shell"
    case explosives
    case expressLoader = "express-loader"
    case expressSplitter = "express-splitter"
    case expressTransportBelt = "express-transport-belt"
    case expressUndergroundBelt = "express-underground-belt"
    case fastInserter = "fast-inserter"
    case fastLoader = "fast-loader"
    case fastSplitter = "fast-splitter"
    case fastTransportBelt = "fast-transport-belt"
    case fastUndergroundBelt = "fast-underground-belt"
    case fillCrudeOilBarrel = "fill-crude-oil-barrel"
    case fillHeavyOilBarrel = "fill-heavy-oil-barrel"
    case fillLightOilBarrel = "fill-light-oil-barrel"
    case fillLubricantBarrel = "fill-lubricant-barrel"
    case fillPetroleumGasBarrel = "fill-petroleum-gas-barrel"
    case fillSulfuricAcidBarrel = "fill-sulfuric-acid-barrel"
    case fillWaterBarrel = "fill-water-barrel"
    case filterInserter = "filter-inserter"
    case firearmMagazine = "firearm-magazine"
    case flamethrower
    case flamethrowerAmmo = "flamethrower-ammo"
    case flamethrowerTurret = "flamethrower-turret"
    case fluidWagon = "fluid-wagon"
    case flyingRobotFrame = "flying-robot-frame"
    case fusionReactorEquipment = "fusion-reactor-equipment"
    case gate
    case greenWire = "green-wire"
    case grenade
    case gunTurret = "gun-turret"
    case hazardConcrete = "hazard-concrete"
    case heatExchanger = "heat-exchanger"
    case heatPipe = "heat-pipe"
    case heavyArmor = "heavy-armor"
    case heavyOilCracking = "heavy-oil-cracking"
    case inserter
    case ironChest = "iron-chest"
    case ironGearWheel = "iron-gear-wheel"
    case ironPlate = "iron-plate"
    case ironStick = "iron-stick"
    case kovarexEnrichmentProcess = "kovarex-enrichment-process"
    case lab
    case landMine = "land-mine"
    case landfill
    case laserTurret = "laser-turret"
    case lightArmor = "light-armor"
    case lightOilCracking = "light-oil-cracking"
    case loader
    case locomotive
    case logisticChestActiveProvider = "logistic-chest-active-provider"
    case logisticChestBuffer = "logistic-chest-buffer"
    case logisticChestPassiveProvider = "logistic-chest-passive-provider"
    case logisticChestRequester = "logistic-chest-requester"
    case logisticChestStorage = "logistic-chest-storage"
    case logisticRobot = "logistic-robot"
    case logisticSciencePack = "logistic-science-pack"
    case longHandedInserter = "long-handed-inserter"
    case lowDensityStructure = "low-density-structure"
    case lubricant
    case mediumElectricPole = "medium-electric-pole"
    case militarySciencePack = "military-science-pack"
    case modularArmor = "modular-armor"
    case nightVisionEquipment = "night-vision-equipment"
    case nuclearFuel = "nuclear-fuel"
    case nuclearFuelReprocessing = "nuclear-fuel-reprocessing"
    case nuclearReactor = "nuclear-reactor"
    case offshorePump = "offshore-pump"
    case oilRefinery = "oil-refinery"
    case personalLaserDefenseEquipment = "personal-laser-defense-equipment"
    case personalRoboportEquipment = "personal-roboport-equipment"
    case personalRoboportMk2Equipment = "personal-roboport-mk2-equipment"
    case piercingRoundsMagazine = "piercing-rounds-magazine"
    case piercingShotgunShell = "piercing-shotgun-shell"
    case pipe
    case pipeToGround = "pipe-to-ground"
    case pistol
    case plasticBar = "plastic-bar"
    case playerPort = "player-port"
    case poisonCapsule = "poison-capsule"
    case powerArmor = "power-armor"
    case powerArmorMk2 = "power-armor-mk2"
    case powerSwitch = "power-switch"
    case processingUnit = "processing-unit"
    case productionSciencePack = "production-science-pack"
    case productivityModule = "productivity-module"
    case productivityModule2 = "productivity-module-2"
    case productivityModule3 = "productivity-module-3"
    case programmableSpeaker = "programmable-speaker"
    case pump
    case pumpjack
    case radar
    case rail
    case railChainSignal = "rail-chain-signal"
    case railSignal = "rail-signal"
    case railgun
    case railgunDart = "railgun-dart"
    case redWire = "red-wire"
    case refinedConcrete = "refined-concrete"
    case refinedHazardConcrete = "refined-hazard-concrete"
    case repairPack = "repair-pack"
    case roboport
    case rocket
    case rocketControlUnit = "rocket-control-unit"
    case rocketFuel = "rocket-fuel"
    case rocketLauncher = "rocket-launcher"
    case rocketPart = "rocket-part"
    case rocketSilo = "rocket-silo"
    case satellite
    case shotgun
    case shotgunShell = "shotgun-shell"
    case slowdownCapsule = "slowdown-capsule"
    case smallElectricPole = "small-electric-pole"
    case smallLamp = "small-lamp"
    case smallPlane = "small-plane"
    case solarPanel = "solar-panel"
    case solarPanelEquipment = "solar-panel-equipment"
    case solidFuelFromHeavyOil = "solid-fuel-from-heavy-oil"
    case solidFuelFromLightOil = "solid-fuel-from-light-oil"
    case solidFuelFromPetroleumGas = "solid-fuel-from-petroleum-gas"
    case speedModule = "speed-module"
    case speedModule2 = "speed-module-2"
    case speedModule3 = "speed-module-3"
    case spidertron
    case spidertronRemote = "spidertron-remote"
    case splitter
    case stackFilterInserter = "stack-filter-inserter"
    case stackInserter = "stack-inserter"
    case steamEngine = "steam-engine"
    case steamTurbine = "steam-turbine"
    case steelChest = "steel-chest"
    case steelFurnace = "steel-furnace"
    case steelPlate = "steel-plate"
    case stoneBrick = "stone-brick"
    case stoneFurnace = "stone-furnace"
    case stoneWall = "stone-wall"
    case storageTank = "storage-tank"
    case submachineGun = "submachine-gun"
    case substation
    case sulfur
    case sulfuricAcid = "sulfuric-acid"
    case tank
    case trainStop = "train-stop"
    case transportBelt = "transport-belt"
    case undergroundBelt = "underground-belt"
    case uraniumCannonShell = "uranium-cannon-shell"
    case uraniumFuelCell = "uranium-fuel-cell"
    case uraniumProcessing = "uranium-processing"
    case uraniumRoundsMagazine = "uranium-rounds-magazine"
    case utilitySciencePack = "utility-science-pack"
    case woodenChest = "wooden-chest"
}