public enum TechnologyPrototypeName: String, PrototypeName {
    case advancedElectronics = "advanced-electronics"
    case advancedElectronics2 = "advanced-electronics-2"
    case advancedMaterialProcessing = "advanced-material-processing"
    case advancedMaterialProcessing2 = "advanced-material-processing-2"
    case advancedOilProcessing = "advanced-oil-processing"
    case artillery
    case artilleryShellRange1 = "artillery-shell-range-1"
    case artilleryShellSpeed1 = "artillery-shell-speed-1"
    case atomicBomb = "atomic-bomb"
    case automatedRailTransportation = "automated-rail-transportation"
    case automation
    case automation2 = "automation-2"
    case automation3 = "automation-3"
    case automobilism
    case battery
    case batteryEquipment = "battery-equipment"
    case batteryMk2Equipment = "battery-mk2-equipment"
    case beltImmunityEquipment = "belt-immunity-equipment"
    case brakingForce1 = "braking-force-1"
    case brakingForce2 = "braking-force-2"
    case brakingForce3 = "braking-force-3"
    case brakingForce4 = "braking-force-4"
    case brakingForce5 = "braking-force-5"
    case brakingForce6 = "braking-force-6"
    case brakingForce7 = "braking-force-7"
    case chemicalSciencePack = "chemical-science-pack"
    case circuitNetwork = "circuit-network"
    case cliffExplosives = "cliff-explosives"
    case coalLiquefaction = "coal-liquefaction"
    case combatRobotics = "combat-robotics"
    case combatRobotics2 = "combat-robotics-2"
    case combatRobotics3 = "combat-robotics-3"
    case concrete
    case constructionRobotics = "construction-robotics"
    case dischargeDefenseEquipment = "discharge-defense-equipment"
    case effectTransmission = "effect-transmission"
    case effectivityModule = "effectivity-module"
    case effectivityModule2 = "effectivity-module-2"
    case effectivityModule3 = "effectivity-module-3"
    case electricEnergyAccumulators = "electric-energy-accumulators"
    case electricEnergyDistribution1 = "electric-energy-distribution-1"
    case electricEnergyDistribution2 = "electric-energy-distribution-2"
    case electricEngine = "electric-engine"
    case electronics
    case energyShieldEquipment = "energy-shield-equipment"
    case energyShieldMk2Equipment = "energy-shield-mk2-equipment"
    case energyWeaponsDamage1 = "energy-weapons-damage-1"
    case energyWeaponsDamage2 = "energy-weapons-damage-2"
    case energyWeaponsDamage3 = "energy-weapons-damage-3"
    case energyWeaponsDamage4 = "energy-weapons-damage-4"
    case energyWeaponsDamage5 = "energy-weapons-damage-5"
    case energyWeaponsDamage6 = "energy-weapons-damage-6"
    case energyWeaponsDamage7 = "energy-weapons-damage-7"
    case engine
    case exoskeletonEquipment = "exoskeleton-equipment"
    case explosiveRocketry = "explosive-rocketry"
    case explosives
    case fastInserter = "fast-inserter"
    case flamethrower
    case flammables
    case fluidHandling = "fluid-handling"
    case fluidWagon = "fluid-wagon"
    case followerRobotCount1 = "follower-robot-count-1"
    case followerRobotCount2 = "follower-robot-count-2"
    case followerRobotCount3 = "follower-robot-count-3"
    case followerRobotCount4 = "follower-robot-count-4"
    case followerRobotCount5 = "follower-robot-count-5"
    case followerRobotCount6 = "follower-robot-count-6"
    case followerRobotCount7 = "follower-robot-count-7"
    case fusionReactorEquipment = "fusion-reactor-equipment"
    case gates
    case heavyArmor = "heavy-armor"
    case inserterCapacityBonus1 = "inserter-capacity-bonus-1"
    case inserterCapacityBonus2 = "inserter-capacity-bonus-2"
    case inserterCapacityBonus3 = "inserter-capacity-bonus-3"
    case inserterCapacityBonus4 = "inserter-capacity-bonus-4"
    case inserterCapacityBonus5 = "inserter-capacity-bonus-5"
    case inserterCapacityBonus6 = "inserter-capacity-bonus-6"
    case inserterCapacityBonus7 = "inserter-capacity-bonus-7"
    case kovarexEnrichmentProcess = "kovarex-enrichment-process"
    case landMine = "land-mine"
    case landfill
    case laser
    case laserTurretSpeed1 = "laser-turret-speed-1"
    case laserTurretSpeed2 = "laser-turret-speed-2"
    case laserTurretSpeed3 = "laser-turret-speed-3"
    case laserTurretSpeed4 = "laser-turret-speed-4"
    case laserTurretSpeed5 = "laser-turret-speed-5"
    case laserTurretSpeed6 = "laser-turret-speed-6"
    case laserTurretSpeed7 = "laser-turret-speed-7"
    case laserTurrets = "laser-turrets"
    case logisticRobotics = "logistic-robotics"
    case logisticSciencePack = "logistic-science-pack"
    case logisticSystem = "logistic-system"
    case logistics
    case logistics2 = "logistics-2"
    case logistics3 = "logistics-3"
    case lowDensityStructure = "low-density-structure"
    case lubricant
    case military
    case military2 = "military-2"
    case military3 = "military-3"
    case military4 = "military-4"
    case militarySciencePack = "military-science-pack"
    case miningProductivity1 = "mining-productivity-1"
    case miningProductivity2 = "mining-productivity-2"
    case miningProductivity3 = "mining-productivity-3"
    case miningProductivity4 = "mining-productivity-4"
    case modularArmor = "modular-armor"
    case modules
    case nightVisionEquipment = "night-vision-equipment"
    case nuclearFuelReprocessing = "nuclear-fuel-reprocessing"
    case nuclearPower = "nuclear-power"
    case oilProcessing = "oil-processing"
    case optics
    case personalLaserDefenseEquipment = "personal-laser-defense-equipment"
    case personalRoboportEquipment = "personal-roboport-equipment"
    case personalRoboportMk2Equipment = "personal-roboport-mk2-equipment"
    case physicalProjectileDamage1 = "physical-projectile-damage-1"
    case physicalProjectileDamage2 = "physical-projectile-damage-2"
    case physicalProjectileDamage3 = "physical-projectile-damage-3"
    case physicalProjectileDamage4 = "physical-projectile-damage-4"
    case physicalProjectileDamage5 = "physical-projectile-damage-5"
    case physicalProjectileDamage6 = "physical-projectile-damage-6"
    case physicalProjectileDamage7 = "physical-projectile-damage-7"
    case plastics
    case powerArmor = "power-armor"
    case powerArmorMk2 = "power-armor-mk2"
    case productionSciencePack = "production-science-pack"
    case productivityModule = "productivity-module"
    case productivityModule2 = "productivity-module-2"
    case productivityModule3 = "productivity-module-3"
    case railSignals = "rail-signals"
    case railway
    case refinedFlammables1 = "refined-flammables-1"
    case refinedFlammables2 = "refined-flammables-2"
    case refinedFlammables3 = "refined-flammables-3"
    case refinedFlammables4 = "refined-flammables-4"
    case refinedFlammables5 = "refined-flammables-5"
    case refinedFlammables6 = "refined-flammables-6"
    case refinedFlammables7 = "refined-flammables-7"
    case researchSpeed1 = "research-speed-1"
    case researchSpeed2 = "research-speed-2"
    case researchSpeed3 = "research-speed-3"
    case researchSpeed4 = "research-speed-4"
    case researchSpeed5 = "research-speed-5"
    case researchSpeed6 = "research-speed-6"
    case robotics
    case rocketControlUnit = "rocket-control-unit"
    case rocketFuel = "rocket-fuel"
    case rocketSilo = "rocket-silo"
    case rocketry
    case solarEnergy = "solar-energy"
    case solarPanelEquipment = "solar-panel-equipment"
    case spaceSciencePack = "space-science-pack"
    case speedModule = "speed-module"
    case speedModule2 = "speed-module-2"
    case speedModule3 = "speed-module-3"
    case spidertron
    case stackInserter = "stack-inserter"
    case steelAxe = "steel-axe"
    case steelProcessing = "steel-processing"
    case stoneWalls = "stone-walls"
    case strongerExplosives1 = "stronger-explosives-1"
    case strongerExplosives2 = "stronger-explosives-2"
    case strongerExplosives3 = "stronger-explosives-3"
    case strongerExplosives4 = "stronger-explosives-4"
    case strongerExplosives5 = "stronger-explosives-5"
    case strongerExplosives6 = "stronger-explosives-6"
    case strongerExplosives7 = "stronger-explosives-7"
    case sulfurProcessing = "sulfur-processing"
    case tanks
    case toolbelt
    case turrets
    case uraniumAmmo = "uranium-ammo"
    case uraniumProcessing = "uranium-processing"
    case utilitySciencePack = "utility-science-pack"
    case weaponShootingSpeed1 = "weapon-shooting-speed-1"
    case weaponShootingSpeed2 = "weapon-shooting-speed-2"
    case weaponShootingSpeed3 = "weapon-shooting-speed-3"
    case weaponShootingSpeed4 = "weapon-shooting-speed-4"
    case weaponShootingSpeed5 = "weapon-shooting-speed-5"
    case weaponShootingSpeed6 = "weapon-shooting-speed-6"
    case workerRobotsSpeed1 = "worker-robots-speed-1"
    case workerRobotsSpeed2 = "worker-robots-speed-2"
    case workerRobotsSpeed3 = "worker-robots-speed-3"
    case workerRobotsSpeed4 = "worker-robots-speed-4"
    case workerRobotsSpeed5 = "worker-robots-speed-5"
    case workerRobotsSpeed6 = "worker-robots-speed-6"
    case workerRobotsStorage1 = "worker-robots-storage-1"
    case workerRobotsStorage2 = "worker-robots-storage-2"
    case workerRobotsStorage3 = "worker-robots-storage-3"
}