public enum TilePrototypeName: String, PrototypeName {
    case acidRefinedConcrete = "acid-refined-concrete"
    case blackRefinedConcrete = "black-refined-concrete"
    case blueRefinedConcrete = "blue-refined-concrete"
    case brownRefinedConcrete = "brown-refined-concrete"
    case concrete
    case cyanRefinedConcrete = "cyan-refined-concrete"
    case deepwater
    case deepwaterGreen = "deepwater-green"
    case dirt1 = "dirt-1"
    case dirt2 = "dirt-2"
    case dirt3 = "dirt-3"
    case dirt4 = "dirt-4"
    case dirt5 = "dirt-5"
    case dirt6 = "dirt-6"
    case dirt7 = "dirt-7"
    case dryDirt = "dry-dirt"
    case grass1 = "grass-1"
    case grass2 = "grass-2"
    case grass3 = "grass-3"
    case grass4 = "grass-4"
    case greenRefinedConcrete = "green-refined-concrete"
    case hazardConcreteLeft = "hazard-concrete-left"
    case hazardConcreteRight = "hazard-concrete-right"
    case labDark1 = "lab-dark-1"
    case labDark2 = "lab-dark-2"
    case labWhite = "lab-white"
    case landfill
    case nuclearGround = "nuclear-ground"
    case orangeRefinedConcrete = "orange-refined-concrete"
    case outOfMap = "out-of-map"
    case pinkRefinedConcrete = "pink-refined-concrete"
    case purpleRefinedConcrete = "purple-refined-concrete"
    case redDesert0 = "red-desert-0"
    case redDesert1 = "red-desert-1"
    case redDesert2 = "red-desert-2"
    case redDesert3 = "red-desert-3"
    case redRefinedConcrete = "red-refined-concrete"
    case refinedConcrete = "refined-concrete"
    case refinedHazardConcreteLeft = "refined-hazard-concrete-left"
    case refinedHazardConcreteRight = "refined-hazard-concrete-right"
    case sand1 = "sand-1"
    case sand2 = "sand-2"
    case sand3 = "sand-3"
    case stonePath = "stone-path"
    case tileUnknown = "tile-unknown"
    case tutorialGrid = "tutorial-grid"
    case water
    case waterGreen = "water-green"
    case waterMud = "water-mud"
    case waterShallow = "water-shallow"
    case yellowRefinedConcrete = "yellow-refined-concrete"
}