public enum TreePrototypeName: String, PrototypeName {
    case deadDryHairyTree = "dead-dry-hairy-tree"
    case deadGreyTrunk = "dead-grey-trunk"
    case deadTreeDesert = "dead-tree-desert"
    case dryHairyTree = "dry-hairy-tree"
    case dryTree = "dry-tree"
    case tree01 = "tree-01"
    case tree02 = "tree-02"
    case tree02Red = "tree-02-red"
    case tree03 = "tree-03"
    case tree04 = "tree-04"
    case tree05 = "tree-05"
    case tree06 = "tree-06"
    case tree06Brown = "tree-06-brown"
    case tree07 = "tree-07"
    case tree08 = "tree-08"
    case tree08Brown = "tree-08-brown"
    case tree08Red = "tree-08-red"
    case tree09 = "tree-09"
    case tree09Brown = "tree-09-brown"
    case tree09Red = "tree-09-red"
}