public enum AnyItemPrototypeName: String {
    case accumulator
    case advancedCircuit = "advanced-circuit"
    case arithmeticCombinator = "arithmetic-combinator"
    case artilleryShell = "artillery-shell"
    case artilleryTargetingRemote = "artillery-targeting-remote"
    case artilleryTurret = "artillery-turret"
    case artilleryWagon = "artillery-wagon"
    case artilleryWagonCannon = "artillery-wagon-cannon"
    case assemblingMachine1 = "assembling-machine-1"
    case assemblingMachine2 = "assembling-machine-2"
    case assemblingMachine3 = "assembling-machine-3"
    case atomicBomb = "atomic-bomb"
    case automationSciencePack = "automation-science-pack"
    case battery
    case batteryEquipment = "battery-equipment"
    case batteryMk2Equipment = "battery-mk2-equipment"
    case beacon
    case beltImmunityEquipment = "belt-immunity-equipment"
    case bigElectricPole = "big-electric-pole"
    case blueprint
    case blueprintBook = "blueprint-book"
    case boiler
    case burnerGenerator = "burner-generator"
    case burnerInserter = "burner-inserter"
    case burnerMiningDrill = "burner-mining-drill"
    case cannonShell = "cannon-shell"
    case car
    case cargoWagon = "cargo-wagon"
    case centrifuge
    case chemicalPlant = "chemical-plant"
    case chemicalSciencePack = "chemical-science-pack"
    case cliffExplosives = "cliff-explosives"
    case clusterGrenade = "cluster-grenade"
    case coal
    case coin
    case combatShotgun = "combat-shotgun"
    case computer
    case concrete
    case constantCombinator = "constant-combinator"
    case constructionRobot = "construction-robot"
    case copperCable = "copper-cable"
    case copperOre = "copper-ore"
    case copperPlate = "copper-plate"
    case crashSiteAssemblingMachine1Broken = "crash-site-assembling-machine-1-broken"
    case crashSiteAssemblingMachine1Repaired = "crash-site-assembling-machine-1-repaired"
    case crashSiteAssemblingMachine2Broken = "crash-site-assembling-machine-2-broken"
    case crashSiteAssemblingMachine2Repaired = "crash-site-assembling-machine-2-repaired"
    case crashSiteChest1 = "crash-site-chest-1"
    case crashSiteChest2 = "crash-site-chest-2"
    case crashSiteElectricPole = "crash-site-electric-pole"
    case crashSiteGenerator = "crash-site-generator"
    case crashSiteLabBroken = "crash-site-lab-broken"
    case crashSiteLabRepaired = "crash-site-lab-repaired"
    case crudeOilBarrel = "crude-oil-barrel"
    case deciderCombinator = "decider-combinator"
    case deconstructionPlanner = "deconstruction-planner"
    case defenderCapsule = "defender-capsule"
    case destroyerCapsule = "destroyer-capsule"
    case dischargeDefenseEquipment = "discharge-defense-equipment"
    case dischargeDefenseRemote = "discharge-defense-remote"
    case distractorCapsule = "distractor-capsule"
    case dummySteelAxe = "dummy-steel-axe"
    case effectivityModule = "effectivity-module"
    case effectivityModule2 = "effectivity-module-2"
    case effectivityModule3 = "effectivity-module-3"
    case electricEnergyInterface = "electric-energy-interface"
    case electricEngineUnit = "electric-engine-unit"
    case electricFurnace = "electric-furnace"
    case electricMiningDrill = "electric-mining-drill"
    case electronicCircuit = "electronic-circuit"
    case emptyBarrel = "empty-barrel"
    case energyShieldEquipment = "energy-shield-equipment"
    case energyShieldMk2Equipment = "energy-shield-mk2-equipment"
    case engineUnit = "engine-unit"
    case exoskeletonEquipment = "exoskeleton-equipment"
    case explosiveCannonShell = "explosive-cannon-shell"
    case explosiveRocket = "explosive-rocket"
    case explosiveUraniumCannonShell = "explosive-uranium-cannon-shell"
    case explosives
    case expressLoader = "express-loader"
    case expressSplitter = "express-splitter"
    case expressTransportBelt = "express-transport-belt"
    case expressUndergroundBelt = "express-underground-belt"
    case fastInserter = "fast-inserter"
    case fastLoader = "fast-loader"
    case fastSplitter = "fast-splitter"
    case fastTransportBelt = "fast-transport-belt"
    case fastUndergroundBelt = "fast-underground-belt"
    case filterInserter = "filter-inserter"
    case firearmMagazine = "firearm-magazine"
    case flamethrower
    case flamethrowerAmmo = "flamethrower-ammo"
    case flamethrowerTurret = "flamethrower-turret"
    case fluidWagon = "fluid-wagon"
    case flyingRobotFrame = "flying-robot-frame"
    case fusionReactorEquipment = "fusion-reactor-equipment"
    case gate
    case greenWire = "green-wire"
    case grenade
    case gunTurret = "gun-turret"
    case hazardConcrete = "hazard-concrete"
    case heatExchanger = "heat-exchanger"
    case heatInterface = "heat-interface"
    case heatPipe = "heat-pipe"
    case heavyArmor = "heavy-armor"
    case heavyOilBarrel = "heavy-oil-barrel"
    case infinityChest = "infinity-chest"
    case infinityPipe = "infinity-pipe"
    case inserter
    case ironChest = "iron-chest"
    case ironGearWheel = "iron-gear-wheel"
    case ironOre = "iron-ore"
    case ironPlate = "iron-plate"
    case ironStick = "iron-stick"
    case itemUnknown = "item-unknown"
    case itemWithInventory = "item-with-inventory"
    case itemWithLabel = "item-with-label"
    case lab
    case landMine = "land-mine"
    case landfill
    case laserTurret = "laser-turret"
    case lightArmor = "light-armor"
    case lightOilBarrel = "light-oil-barrel"
    case loader
    case locomotive
    case logisticChestActiveProvider = "logistic-chest-active-provider"
    case logisticChestBuffer = "logistic-chest-buffer"
    case logisticChestPassiveProvider = "logistic-chest-passive-provider"
    case logisticChestRequester = "logistic-chest-requester"
    case logisticChestStorage = "logistic-chest-storage"
    case logisticRobot = "logistic-robot"
    case logisticSciencePack = "logistic-science-pack"
    case longHandedInserter = "long-handed-inserter"
    case lowDensityStructure = "low-density-structure"
    case lubricantBarrel = "lubricant-barrel"
    case mediumElectricPole = "medium-electric-pole"
    case militarySciencePack = "military-science-pack"
    case modularArmor = "modular-armor"
    case nightVisionEquipment = "night-vision-equipment"
    case nuclearFuel = "nuclear-fuel"
    case nuclearReactor = "nuclear-reactor"
    case offshorePump = "offshore-pump"
    case oilRefinery = "oil-refinery"
    case personalLaserDefenseEquipment = "personal-laser-defense-equipment"
    case personalRoboportEquipment = "personal-roboport-equipment"
    case personalRoboportMk2Equipment = "personal-roboport-mk2-equipment"
    case petroleumGasBarrel = "petroleum-gas-barrel"
    case piercingRoundsMagazine = "piercing-rounds-magazine"
    case piercingShotgunShell = "piercing-shotgun-shell"
    case pipe
    case pipeToGround = "pipe-to-ground"
    case pistol
    case plasticBar = "plastic-bar"
    case playerPort = "player-port"
    case poisonCapsule = "poison-capsule"
    case powerArmor = "power-armor"
    case powerArmorMk2 = "power-armor-mk2"
    case powerSwitch = "power-switch"
    case processingUnit = "processing-unit"
    case productionSciencePack = "production-science-pack"
    case productivityModule = "productivity-module"
    case productivityModule2 = "productivity-module-2"
    case productivityModule3 = "productivity-module-3"
    case programmableSpeaker = "programmable-speaker"
    case pump
    case pumpjack
    case radar
    case railChainSignal = "rail-chain-signal"
    case railSignal = "rail-signal"
    case railgun
    case railgunDart = "railgun-dart"
    case rawFish = "raw-fish"
    case redWire = "red-wire"
    case refinedConcrete = "refined-concrete"
    case refinedHazardConcrete = "refined-hazard-concrete"
    case repairPack = "repair-pack"
    case roboport
    case rocket
    case rocketControlUnit = "rocket-control-unit"
    case rocketFuel = "rocket-fuel"
    case rocketLauncher = "rocket-launcher"
    case rocketPart = "rocket-part"
    case rocketSilo = "rocket-silo"
    case satellite
    case selectionTool = "selection-tool"
    case shotgun
    case shotgunShell = "shotgun-shell"
    case simpleEntityWithForce = "simple-entity-with-force"
    case simpleEntityWithOwner = "simple-entity-with-owner"
    case slowdownCapsule = "slowdown-capsule"
    case smallElectricPole = "small-electric-pole"
    case smallLamp = "small-lamp"
    case smallPlane = "small-plane"
    case solarPanel = "solar-panel"
    case solarPanelEquipment = "solar-panel-equipment"
    case solidFuel = "solid-fuel"
    case spaceSciencePack = "space-science-pack"
    case speedModule = "speed-module"
    case speedModule2 = "speed-module-2"
    case speedModule3 = "speed-module-3"
    case spidertron
    case spidertronRocketLauncher1 = "spidertron-rocket-launcher-1"
    case spidertronRocketLauncher2 = "spidertron-rocket-launcher-2"
    case spidertronRocketLauncher3 = "spidertron-rocket-launcher-3"
    case spidertronRocketLauncher4 = "spidertron-rocket-launcher-4"
    case splitter
    case stackFilterInserter = "stack-filter-inserter"
    case stackInserter = "stack-inserter"
    case steamEngine = "steam-engine"
    case steamTurbine = "steam-turbine"
    case steelChest = "steel-chest"
    case steelFurnace = "steel-furnace"
    case steelPlate = "steel-plate"
    case stone
    case stoneBrick = "stone-brick"
    case stoneFurnace = "stone-furnace"
    case stoneWall = "stone-wall"
    case storageTank = "storage-tank"
    case submachineGun = "submachine-gun"
    case substation
    case sulfur
    case sulfuricAcidBarrel = "sulfuric-acid-barrel"
    case tank
    case tankCannon = "tank-cannon"
    case tankFlamethrower = "tank-flamethrower"
    case tankMachineGun = "tank-machine-gun"
    case trainStop = "train-stop"
    case transportBelt = "transport-belt"
    case undergroundBelt = "underground-belt"
    case uranium235 = "uranium-235"
    case uranium238 = "uranium-238"
    case uraniumCannonShell = "uranium-cannon-shell"
    case uraniumFuelCell = "uranium-fuel-cell"
    case uraniumOre = "uranium-ore"
    case uraniumRoundsMagazine = "uranium-rounds-magazine"
    case usedUpUraniumFuelCell = "used-up-uranium-fuel-cell"
    case utilitySciencePack = "utility-science-pack"
    case vehicleMachineGun = "vehicle-machine-gun"
    case waterBarrel = "water-barrel"
    case wood
    case woodenChest = "wooden-chest"
}
